- name: Provision Vagrant
  hosts: all
  become: yes
  user: vagrant
  vars:
    - mysql_pass: 123asd3d
    - mysql_database: eightwizards
    - vagrant_folder: /vagrant
    - vagrant_project_folder: /vagrant/eightwizards
    - django_settings: eightwizards.settings.local
  handlers:
    - name: Restart MySQL
      service: name=mysql state=restarted
    - name: Restart Redis
      service: name=redis-server state=restarted

  tasks:
    - name: Install MySQL packages
      apt: pkg={{ item }} state=installed update_cache=yes
      with_items:
           - mysql-server
           - mysql-client
           - python-mysqldb

    - name: Update MySQL root password for all wizard accounts
      mysql_user: name=root host={{ item }} password={{ mysql_pass }} state=present
      with_items:
        - 127.0.0.1
        - ::1
        - localhost

    - name: Copy the root credentials as .my.cnf file
      template: src=mysql.cnf.j2 dest=~/.my.cnf mode=0600


    - name: Ensure Anonymous user(s) are not in the database
      mysql_user: name='' host={{ item }} state=absent
      with_items:
        - localhost

    - name: Create the project database
      mysql_db: name={{ mysql_database }} state=present encoding=utf8

    - name: Remove the test database
      mysql_db: name=test state=absent
      notify:
        - Restart MySQL

    - name: Install Redis server
      apt: pkg={{ item }} state=installed update_cache=yes
      with_items:
        - redis-server
      notify:
        - Restart Redis

    - name: Install frontend stack stuff
      apt: name={{ item }} state=installed update_cache=yes
      with_items:
        - nodejs
        - nodejs-legacy
        - npm
        - ruby

    - name: Copy package.json to vagrant's fs
      copy: src="package.json" dest={{ vagrant_folder }}

    - name: Install npm packages
      npm: path={{ vagrant_folder }}

    - name: Install SASS
      gem:
        name: sass
        user_install: no

    - name: Install Bower dependecies
      bower: name={{ item }} path={{ vagrant_project_folder }}/static relative_execpath=~/node_modules/.bin
      with_items:
        - foundation-sites
        - jquery

    # - name: Run Gulp
    #  command: gulp

    - name: Instal python related/driver packages
      apt: name={{ item }} state=installed update_cache=yes
      with_items:
        - python3-dev
        - python3-pip
        - libmysqlclient-dev
        - libjpeg8-dev

    - name: Install Python packages
      pip: requirements={{ vagrant_folder }}/requirements.txt executable=pip3

    - name: Django Migrate DB
      command : 'python3 {{ vagrant_project_folder }}/manage.py migrate --settings={{ django_settings }}'

    - name: Start Django Test Server
      command: 'python3 {{ vagrant_project_folder }}/manage.py runserver 0.0.0.0:9999 --settings={{ django_settings }}'